### ISSUE TITLE
Assignment record function does not complete request

### ISSUE THREAD

**Issue by goatmoat** [sjacorg/bayanat#10]
Assignment of records/incidents. Assigning an incident to another reviewer/user stops short of having a small rotating 'processing' circle rotate continuously, new assignment will add another rotating circle, and so forth, but will not complete the assignment (see image). When checking the assigned to me section of other users, these remain empty.

![Test_assignment](https://user-images.githubusercontent.com/48836862/115563416-cef7e700-a2b7-11eb-84c2-4926b48dd71f.png)

**Comment by sjacgit** [comment]
Thanks for your report. Have you set up celery to work properly with Bayanat? If so, can you please check for any errors in celery's service log after a bulk-update? Also, can you please check for any errors in the browser's console?

**Comment by goatmoat** [comment]
Thanks for this. We have Celery working under this example task command:
celery -A enferno.tasks worker

Latest logs gave us this:
[2021-05-05 13:16:03,912: WARNING/ForkPoolWorker-2] Incidents Bulk Update Successful
[2021-05-05 13:16:35,732: WARNING/ForkPoolWorker-2] Incidents Bulk Update Successful
[2021-05-05 13:17:45,349: WARNING/ForkPoolWorker-2] Incidents Bulk Update Successful
[2021-05-05 13:21:31,220: WARNING/ForkPoolWorker-2] Incidents Bulk Update Successful
[2021-05-05 13:49:45,870: WARNING/ForkPoolWorker-2] Incidents Bulk Update Successful

It appears that the bulk update function is now working with the upgrade to V1.3. Although we're not sure if this is, as with the secondary components issue, consistent.

**Comment by goatmoat** [comment]
After more testing, this appears to be inconsistent in V1.3 as well. Some assignments happen, some don't and we have the yellow circles appear in multitude as before. This is with the task command of Celery running as stated above. So this issue is not resolved for us.

**Comment by sjacgit** [comment]
It's not possible for us to assist without an error. Please send us the information we requested in order for us to take a look.

Also, it seems you're using celery (and maybe the flask app?) as a command and not a systemd service. This is not recommended and you should run the flask app and celery as services.

**Comment by sjacgit** [comment]
Hello again. Have you had a change to test this issue again and provide us with any errors?

**Comment by goatmoat** [comment]
yes, we tested this issue again, and like with V1.3, V1.4 had the same problem persist. There appeared to be some assigning, but it was random and as mentioned in the other issue, we believe it's related to the same non-subscriptable issue as with the labels. Some assigning works, others have the yellow rotating circle continue. Any new assignment request will add a new circle until you have four or five circles rotating next to each other...

**Comment by sjacgit** [comment]
It's unlikely that this can be caused by issues in secondary components as bulk operations don't actually involve those items. This is likely to be caused by an incorrect setup of celery. If you follow the steps to setup celery in the [installation manual](https://docs.bayanat.org/en/install#running-celery) you should be able to get this issue fixed.

**Comment by goatmoat** [comment]
With V1.5, and the (re) setup of Celery, this appears now to be working. It so happens this issue occurred at the same time as the secondary components issue and so we thought they were both related to the non-subscription issue, but it appears to be Celery as you indicate. Thank you. It works well now. So this issue can be closed.
