### ISSUE TITLE
Missing Persons

### ISSUE THREAD

**Issue by goatmoat** [sjacorg/bayanat#12]
Upgraded to your latest release on our VPS and tried working on the Missing Person table. Noticed that once we set MISSING_PERSONS = TRUE, nothing turned up, but it blocked API calls for Actors and Incidents. 

We managed to resolve the Incidents, but the Actor blocking was persistent so we eventually turned to MISSING_PERSONS = FALSE. That seemed to do the trick, but so far, no luck on getting the missing persons feature working. Any ideas for the runaround on this issue?

**Comment by sjacgit** [comment]
This is because the missing person extension fields are missing in the Actor table. If you want to activate the missing persons extension, this setting needs to be turned on before the database is created. Please check the documentation website: https://docs.bayanat.org/en/config#missing-persons
