### ISSUE TITLE
Upgrade to bayanat v1.10.2

### ISSUE THREAD

**Issue by hapee** [sjacorg/bayanat#15]
just checking, after the upgrade I get every second:

Jan 20 15:47:23 internationalbasketweaving celery[640]: [2022-01-20 15:47:23,045: WARNING/ForkPoolWorker-2] Process engine - off
Jan 20 15:47:26 internationalbasketweaving celery[640]: [2022-01-20 15:47:26,048: WARNING/ForkPoolWorker-2] Process engine - off
Jan 20 15:47:29 internationalbasketweaving celery[640]: [2022-01-20 15:47:29,052: WARNING/ForkPoolWorker-2] Process engine - off
Jan 20 15:47:32 internationalbasketweaving celery[640]: [2022-01-20 15:47:32,043: WARNING/ForkPoolWorker-2] Process engine - off
Jan 20 15:47:35 internationalbasketweaving celery[640]: [2022-01-20 15:47:35,044: WARNING/ForkPoolWorker-2] Process engine - off

is this an issue?

**Comment by sjacgit** [comment]
This is a debug message to let admin know that deduplication processing is off. You can safely ignore these messages if you have the feature turned off, and we'll hide those messages in the future.

**Comment by hapee** [comment]
Thanks will do with it for now
