### ISSUE TITLE
question about maps

### ISSUE THREAD

**Issue by hapee** [sjacorg/bayanat#16]
so not a bug yet and now feature but just a question, the documentation says:

By default, Bayanat will use OpenStreetMaps tiles servers (https://{s}.tile.osm.org/{z}/{x}/{y}.png) to retreive maps. This can be changed using the setting MAPS_API_ENDPOINT, to use an offline instance of OSM for example.

The default setting in .env is:
# MAPS
MAPS_API_ENDPOINT = ''

when I use that I see this:
![image](https://user-images.githubusercontent.com/379964/164258535-3bb7f30a-0799-4a5e-918c-e831fb93ec89.png)

so how can I use openstreet maps as it is supposed to work?

**Comment by sjacgit** [comment]
Not sure what the issue here. Did you set the `MAPS_API_ENDPOINT` variable to something and this is the result you're seeing?  If you're looking to use OSM servers you actually don't need to set/change this var.

**Comment by sjacgit** [comment]
Unless you're using an offline version or a service other than OSM you don't need to set that var. You can delete/comment that line in .env and should work.

**Comment by hapee** [comment]
You are correct (as always). It is working now so ticket closed, thanks for your support.
