### ISSUE TITLE
Demo login credentials don't work

### ISSUE THREAD

**Issue by johnhess** [sjacorg/bayanat#17]
When I try to log in to demo.bayanat.org using the credentials in README.md, I get the message "Invalid username or password !"

This affects both demo and admin user creds.

**Comment by ahmadko** [comment]
+1

**Comment by ahmadko** [comment]
@johnhess thank you for brining this up, I just pushed a PR with the correct creds, for now, please use the following:
- `demo`/`demo` for [Data Analyst](https://docs.bayanat.org/en/users-groups#data-analyst-da) access level.
- `admin-demo`/`admin` for [Administrator](https://docs.bayanat.org/en/users-groups#administrator) access level.

**Comment by sjacgit** [comment]
Many thanks @ahmadko for responding. The instructions in the readme were out of date unfortunately. We've replaced them with a link to our docs website so we don't have that issue again in case they're changed in the future.
