### ISSUE TITLE
upgrade to 2.0 version

### ISSUE THREAD

**Issue by hapee** [sjacorg/bayanat#35]
**Describe the bug**
I followed the procedure to upgrade to v2.0 but there are some issues:
there are 3 packages required in the requirement.txt that I can not fulfil which might be related to my version of python but 
weasyprint==62.1
numpy==1.26.4
docutils==0.21.1
are not found.

If I change requirements.txt to the latest found versions I can run the script but it returns:
ERROR: botocore 1.34.100 has requirement urllib3<1.27,>=1.25.4; python_version < "3.10", but you'll have urllib3 2.2.2 which is incompatible.
after that is still continues.

But after I restart the services I get a internal service error in the browser and in the syslog I find:
TypeError: 'type' object is not subscriptable
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uwsgi[276663]: --- no python application found, check your startup logs for errors ---

**To Reproduce**
I went back to version 1.34.4 and that is working

**Expected behavior**
a successful upgrade

**Logs**
copied above.

Thanks for support,
Hapee

**Comment by hapee** [comment]
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"

would an upgrade to 22.04 make a difference?

**Comment by sjacgit** [comment]
Yes. Your Ubuntu version comes with Python 3.8. You will need to upgrade to the next version (22.04 LTS) to get 3.10 (at least officially).

**Comment by hapee** [comment]
Thanks, will report back when done!

**Comment by sjacgit** [comment]
Another option is to move to a new system running the fresh version. You only need to move db backup, `config.json` and `.env` files. If upgrading the same system, you should probably back these files up somewhere else just in case.

**Comment by hapee** [comment]
Worked, version 2 is running, next week I will update to the latest version but thanks for the support so far.
