### ISSUE TITLE
How to Share Data Publicly

### ISSUE THREAD

**Issue by zhabiba24** [sjacorg/bayanat#39]
I'm not sure if this is the right place to ask this question - please tell me where else to go if so.

I'm wondering if there is a way I can provide a public view of the Bayanat instance, e.g. allow people to see a subset of the data that has a 'public' label on it? I see there's a way to create read only accounts but nothing public. 

Would I need to create a separate site to show that and consume an API from Bayanat or something like that?

**Comment by sjacgit** [comment]
Unfortunately no, there isn't a way to allow public access to an instance at this time.

We welcome these discussions on: https://community.bayanat.org/
