### ISSUE TITLE
"Mixed Content" error in /admin/locations/#/ 

### ISSUE THREAD

**Issue by oussjarrousse** [sjacorg/bayanat#6]
when https:// is enabled, browsing to /admin/api/locations/ is throwing a "Mixed Content" error.

It seems that the axios call is requesting the api node over http:// not https:// 

<img width="1435" alt="Screenshot 2021-03-10 at 22 27 34" src="https://user-images.githubusercontent.com/1843808/110700727-9234cc80-81f0-11eb-9e5e-ccf1a7085997.png">

I am on a Chrome browser

**Comment by oussjarrousse** [comment]
This issue is not present on Safari

**Comment by sjac-td** [comment]
The issue should now be fixed in v1.2. Can you please update and test again on your end and let us know if it's resolved? Please note that there are some upgrade instructions that you need, it's included in the release notes of v1.2.

**Comment by sjacgit** [comment]
Hello again. Have you had a change to test this issue again in order for us to close it?
